### ISSUE TITLE
subtitles

### ISSUE THREAD

**Issue by williamoliveira** [hola/player#1]
Is there an option to load subtitles from a URL by javascript instead of drag and drop?

By the way, awsome player

**Comment by arikgilad** [comment]
Not yet, but very soon (we hope to release the subtitle api next week).
We will support the following api:

``` html
<iframe src="//hola.org/play_embed#v=xxx.torrent&sub1=eng.srt&sub2=fr.srt"></iframe>
```

or

``` html
<div class="hola-embedded-player" sub1="eng.srt" sub2="fr.srt"></div>
```

The subtitles files can be:
- srt
- vtt
- srt/vtt inside zip file

We will auto-detect the subtitle language from the sub title file name or you can explicity specify the language.
example: sub1=en,xxx.srt

In addition, we hope in the next few weeks to support auto-translation for subtitles from English to any other language.

I will update you once the api is available so you can check it out.

**Comment by williamoliveira** [comment]
Very cool, I will be waiting, thanks

**Comment by arikgilad** [comment]
Hello William,

I have updated our api section in https://github.com/hola/player.

Please check it out and let me know if the api covers your requirements.
You are welcomed to suggest improvements to the api (just send us a pull request).

I hope by mid next week we will have the subtitles api ready.

Arik

**Comment by williamoliveira** [comment]
Hello,
Yes, it does cover.

I have some suggestions however, not related to the subtitles,
that would be:
- custom player dimensions or maybe responsive;
- automatically run the engine application when required if its closed.

**Comment by arikgilad** [comment]
Hi,

We plan to support responsive player in about a month.

I have updated our readme with a TODO section for the new features.

Regarding your 2nd request "automatically run the engine application when 
required if its closed".
Not sure I understood what you mean, please elaborate more on this issue.

Arik

**Comment by williamoliveira** [comment]
Sorry, I mean that, when I have the Hola Application closed (that one on system tray) and I try to play the torrent demos here on the repository, it tells me to download the application with a big "Get Hola Media Player" button, would be cool if it could detect if I already have it installed an automatically run the application instead

**Comment by arikgilad** [comment]
We are going to support auto-start  of the hola if it is closed but it will probably take another 1-2 months before we implement it.

We just released our first version of the embedded player that supports subtitles.
I have updated the readme with links to live demo of the subtitle feature.
Please check it out and let me know of any bug or missing feature.
Note, we are going to release this week json support for subtitles download (and maybe even xml).
Looking forward for your feedback.

**Comment by williamoliveira** [comment]
It's awsome :)
I just have one question, can the subtitles be named to the name of the language, like "English" without the file name ?

**Comment by arikgilad** [comment]
We are still working on the subtitles UI.
Soon we will fix in the following way:
- Show language flag icon
- Show the language translated full name
- On hover, show full info
  Example:
  [Spain flag] Espanol
