### ISSUE TITLE
Antivirus detect hola 

### ISSUE THREAD

**Issue by vladaaa1234** [hola/player#11]
My antivirus detect hola setup like a virus, and blocking me to instal player ?

**Comment by xderry** [comment]
Hi,

Please email us the exact full message details, and the anti-virus version, and we will report this false positive to the anti-virus vendor.

Thanks,
Derry

**Comment by xavico** [comment]
We think the issue has been solved now. If it happens for you again please re-open this issue, and provide us the exact message and name and version of the anti virus.
