### ISSUE TITLE
The MP4 and all videos open on default browser Hola!

### ISSUE THREAD

**Issue by jcandsv** [hola/player#12]
First of all... Great plugin!!

This was fixed a few days ago, but I tried en many computers and  It works fine in 3 computer. And the others (5) works with the popup default browser.. Why? I have Windows 10 in all computers and My Browser is google chrome.

Apologize for my english, It is not my native language. Spanish here :)

<img src="http://kinesis.tv/wp-content/uploads/other.jpg" alt="screenshot" style="max-width:100%;">

**Comment by xderry** [comment]
Thanks for the bug report! We are checking this out, trying to reproduce the problem on our end. I hope by tomorrow we will have answers.

**Comment by xavico** [comment]
We think we solved this issue. In the next couple of hours we will release it.

**Comment by xavico** [comment]
The bug was fixed. If you still encounter this problem please reopen this issue.
