### ISSUE TITLE
GET chrome-extension://gkojfkhlekighikafcpjkiklfbnlmeio/icon.png?rc=1440582098214 net::ERR_FAILED

### ISSUE THREAD

**Issue by datnguyencse** [hola/player#13]
it is not a bug, fix it if you have time

![screenshot_5](https://cloud.githubusercontent.com/assets/11866125/9490393/a60b0618-4c11-11e5-90f2-426d174f1802.png)

**Comment by xavico** [comment]
Thanks for reporting this issue.
We expect to release a fix in the next two weeks.

**Comment by xavico** [comment]
We think we solved this issue. In the next couple of hours we will release it.

**Comment by xavico** [comment]
The bug was fixed. If you still encounter this problem please reopen this issue.
