### ISSUE TITLE
Hi again... !! HOLA!  works in tablet

### ISSUE THREAD

**Issue by jcandsv** [hola/player#14]
Works fine with the app on PlayStore, but I can't display the subtitles?

I guess this is new, but it is Great!

Thanks

**Comment by xavico** [comment]
Thanks for your feedback.
We hope to add the subtitle feature for mobile in the next few weeks.

**Comment by datnguyencse** [comment]
how can I remove subtitle background color?
Thank you.

![screenshot_4](https://cloud.githubusercontent.com/assets/11866125/9519073/da858786-4ce5-11e5-83cf-60cf228d0222.png)

**Comment by xavico** [comment]
Bug closed for possible copyright infringement.  Please note that Hola's TOS 
strictly prohibit copyright infringement.  If you believe that this message is 
in error, please review our bug reporting policy 
https://github.com/hola/player/blob/master/README.md#reporting-bugs and submit a 
new issue.

**Comment by jcandsv** [comment]
Thanks xavico

**Comment by xavico** [comment]
See issue #17
