### ISSUE TITLE
request

### ISSUE THREAD

**Issue by Gishi1** [hola/player#2]
im requesting an option to add the ability to select witch file in the torrent to use for example you have a torrent with 15 mkv files but you want to only use file 2.

param example: select_file="file2.mkv" or maybe by index select_by_index=2

**Comment by arikgilad** [comment]
We are going to implement this feature in the next few weeks.
I will add it to our TODO section in the readme and will update you once it is released.

**Comment by Gishi1** [comment]
any update on this? or a eta?

**Comment by xderry** [comment]
Hi,

Please tell him that you plan to implement this in the coming month or two, but 
in the meantime, we select the largest media file within the torrent, which 
should be good enough in most cases.

Derry

**Comment by arielshu** [comment]
We plan to implement this in the coming month or two. In the meantime, the logic used is to select the largest media file within the torrent, which is good enough in many cases.

**Comment by Gishi1** [comment]
oh quick question is there any way to let the user select a audio track in a dual audio mkv?

**Comment by samurai815** [comment]
Please keep your promise to release on 12-Oct-2015, I'm looking forward to it

**Comment by samurai815** [comment]
I can't understand!
Why do you use "target" while you do not attempt to achieve it?
If the target can be moved anywhere,  you don't understand its meaning.

**Comment by samurai815** [comment]
okay i'm out it never end. I will find another way

**Comment by xavico** [comment]
The bug was fixed. If you still encounter this problem please reopen this issue.
