### ISSUE TITLE
Subtitles Problem

### ISSUE THREAD

**Issue by jcandsv** [hola/player#20]
I have 2 subtitles in my player. English and Spanish... Since yesterday when I click on English subtitles shows Spanish and when i ckick on Spanish subtitles shows the English subtitles... Why? In the past this worked well.. Apologies for my English. The Same happens when I Upload a new subtitle.

Thank you!

**Comment by xavico** [comment]
We think we solved this issue. In the next couple of hours we will release it.

**Comment by xavico** [comment]
The bug was fixed. If you still encounter this problem please reopen this issue.
