### ISSUE TITLE
My internet connection fails with Hola

### ISSUE THREAD

**Issue by jcandsv** [hola/player#24]
Hi, Hola media video works very well, but I lost my internet connection. When I play some video my  internet connection fails... If i want to search google, facebook, youtube or other tab on my browser. I can't. Only the load on my video still working. When I close the video my browser works fine after one minute. This happens to me since today
Apologies for my English.
Thank you!!! Great support !!

**Comment by xderry** [comment]
Hola does not modify your internet connection. Its just another application using TCP/IP.

**Comment by xavico** [comment]
Please add me by Skype: avi_hola.

**Comment by jcandsv** [comment]
My user is downloadjc
I added to my skype

El martes, 6 de octubre de 2015, avi_hola notifications@github.com
escribió:

> Please add me by Skype: avi_hola.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hola/player/issues/24#issuecomment-145805843.

## 

JUAN CARLOS GUERRERO
Enviado desde donde estoy.
