### ISSUE TITLE
Subtitles are not loaded properly

### ISSUE THREAD

**Issue by jcandsv** [hola/player#26]
I use DIV code for embed my player... 

sub1="es,http://URL/ARCHIVE.SRT"
sub2="en,http://URL/ARCHIVE.SRT"

From today does not working. In "Subtitles file technical info" the subtitle url is fine and is uploaded but you can't see... This happens with all subtitles.

 When i uploaded a new subtitle by drop or click upload works fine. Only happens with the embed code.

Apologies if my english is bad. Spanish here :) Thanks!

**Comment by jcandsv** [comment]
Works fine now thanks. Ir was temporary.

**Comment by xavico** [comment]
We are checking to understand where the bug coming from. If it happens again please reopen new issue.
