### ISSUE TITLE
Some torrents are not working

### ISSUE THREAD

**Issue by ghost** [hola/player#29]
Hello guys! The player isn't streaming some torrents, I guess because of special characters in torrent's name.

I'm only getting this message:

> Something went wrong...
> Retry or try another Torrent or Magnet link

I'm using Google Chrome over Windows 7.

Thank you and keep on the great work!

**Comment by xavico** [comment]
Bug closed for possible copyright infringement. Please note that Hola's TOS 
strictly prohibit copyright infringement. If you believe that this message is 
in error, please review our bug reporting policy 
https://github.com/hola/player/blob/master/README.md#reporting-bugs and submit a 
new issue.
