### ISSUE TITLE
Subtitles duplicate themselves on screen

### ISSUE THREAD

**Issue by legionaryu** [hola/player#4]
When I upload a subtitle, it duplicate itself in the screen and keep showing up no matter what I do.

**Comment by michalzh** [comment]
Does it happen to you every time? 
What video URL and subtitle file(s) are you using? 
What's your browser locale and what OS and browser version are you using?

**Comment by legionaryu** [comment]
Hi,
Q: Does it happen to you every time?
Yes.
Q: What video URL and subtitle file(s) are you using?
I'm watching this torrent: http://kickass.to/how-to-train-your-dragon-2-2014-webdl-dvdrip-xvid-maxspeed-t9524000.html with this sub: http://www.opensubtitles.org/en/subtitles/5810591/how-to-train-your-dragon-2-pb
Q: What's your browser locale and what OS and browser version are you using? 
I'm using Firefox 36.0.1 on Windows 8.1.

Here is the generated html from the player, where you can see two elements with the class "vjs-subtitles vjs-text-track":
<div class="mov-title">how to train your dragon 2 2014 webdl dvdrip xvid maxspeed</div><div class="hola-logo"></div><div class="retry_overlay">
        <div class="retry_container">
          <div class="retry_button">
            <svg width="50px" height="50px" viewBox="0 0 50 50">
    <path fill="#FFFFFF" d="M33.4,25.3c-0.3-4.1-3.8-7.2-8-7.5v-1.5c0-0.2-0.2-0.3-0.4-0.2l-4,2.5c-0.2,0.1-0.2,0.3,0,0.4l4,2.5 c0.2,0.1,0.4,0,0.4-0.3v-1.4c3.2,0.4,5.8,2.9,5.7,6c0,3.3-2.8,5.9-6.2,5.9c-3.5,0-6.3-2.8-6.3-6.2l0,0c0-0.4-0.4-0.8-0.8-0.8h-0.5 c-0.5,0-0.8,0.4-0.8,0.8c0,4.3,3.4,8.1,7.9,8.4C29.5,34.3,33.7,30.2,33.4,25.3z"></path>
</svg>

          </div>
          <span class="retry_caption">Reload movie from last point</span>
        </div>
      </div><div style="opacity: 0;" class="buf_overlay">
        <div class="buf_container">
          <div class="buf_spinner bsp_back">
            <svg width="100%" height="100%" viewBox="-1 -1 202 202">
    <path id="buf_rail" d="M 180,100 A 80,80 0 0,1 100,180 A 80,80 0 0,1 20,100 A 80,80 0 0,1 100,20 A 80,80 0 0,1 180,100" style="fill:none"></path>
</svg>

          </div>
          <div style="transform: rotate(56deg);" class="buf_spinner bsp_fore">
            <svg width="100%" height="100%" viewBox="-1 -2 202 202">
    <path id="buf_spincircle" d="M 180,100 A 80,80 0 0,1 180,100" style="fill:none"></path>
</svg>

          </div>
        </div>
        <div class="buf_explanation">
          <span>Buffering</span>
        </div>
      </div><div id="video_sharebutton">
        <svg x="0px" y="0px" width="46px" height="46px" viewBox="2 2 46 46">
  <path fill="#FFFFFF" d="M32.5,28.5c-1,0-1.9,0.4-2.6,1l-8.4-4.2c0-0.1,0-0.2,0-0.3s0-0.2,0-0.3l8.4-4.2c0.7,0.6,1.6,1,2.6,1 c2.2,0,4-1.8,4-4s-1.8-4-4-4s-4,1.8-4,4c0,0.1,0,0.2,0,0.3L20.1,22c-0.7-0.6-1.6-1-2.6-1c-2.2,0-4,1.8-4,4s1.8,4,4,4 c1,0,1.9-0.4,2.6-1l8.4,4.2c0,0.1,0,0.2,0,0.3c0,2.2,1.8,4,4,4s4-1.8,4-4S34.7,28.5,32.5,28.5z"></path>
</svg>

      </div><div><embed style="z-index: 1;" type="application/x-hola-vlc-plugin" class="vjs-tech" allowfullscreen="true" windowless="true" toolbar="false" events="true" branding="false" name="mp_video_player_vlc_api" id="mp_video_player_vlc_api" height="100%" width="100%"></div><div></div><div style="display: none;" tabindex="-1" class="vjs-poster"></div><div class="vjs-text-track-display"><div style="display: block;" class="vjs-subtitles vjs-text-track"><span class="vjs-tt-cue">- Vamos lá.<br>- Cavaleiros passando.</span></div><div style="display: block;" class="vjs-subtitles vjs-text-track"><span class="vjs-tt-cue">- Vamos l�.<br>- Cavaleiros passando.</span></div></div><div class="vjs-loading-spinner"></div><div aria-label="play video" tabindex="0" aria-live="polite" role="button" class="vjs-big-play-button blink"><span aria-hidden="true"></span><svg width="100%" height="100" view-box="0 0 50 50"><use id="umorph" xlink:href="#morph" x="0" y="0"></use></svg></div><div class="vjs-control-bar"><div tabindex="0" aria-live="polite" role="button" class="vjs-play-control vjs-control  vjs-paused"><div class="vjs-control-content"><span class="vjs-control-text">Play</span></div></div><div class="vjs-current-time vjs-time-controls vjs-control"><div aria-live="off" class="vjs-current-time-display"><span class="vjs-control-text">Current Time</span> 1:02:23</div></div><div class="vjs-time-divider"><div><span>/</span></div></div><div class="vjs-duration vjs-time-controls vjs-control"><div aria-live="off" class="vjs-duration-display"><span class="vjs-control-text">Duration Time</span> 1:42:13</div></div><div class="vjs-remaining-time vjs-time-controls vjs-control"><div aria-live="off" class="vjs-remaining-time-display"><span class="vjs-control-text">Remaining Time</span> -39:49</div></div><div class="vjs-live-controls vjs-control"><div aria-live="off" class="vjs-live-display"><span class="vjs-control-text">Stream Type</span>LIVE</div></div><div class="vjs-progress-control vjs-control"><div aria-valuetext="1:02:23" aria-label="video progress bar" class="vjs-progress-holder vjs-slider" tabindex="0" aria-valuemax="100" aria-valuemin="0" aria-valuenow="61.05" role="slider"><div style="width: 100%;" class="vjs-load-progress"><span style="left: 0%; width: 100%;" class="vjs-control-text"><span>Loaded</span>: 0%</span></div><div style="width: 61.05%;" class="vjs-play-progress"><span class="vjs-control-text"><span>Progress</span>: 0%</span></div><div style="left: 61.05%;" aria-live="off" class="vjs-seek-handle vjs-slider-handle"><span class="vjs-control-text">1:02:23</span></div></div></div><div tabindex="0" aria-live="polite" role="button" class="vjs-fullscreen-control vjs-control "><div class="vjs-control-content"><span class="vjs-control-text">Fullscreen</span></div></div><div class="vjs-volume-control vjs-control"><div aria-valuetext="-1%" aria-label="volume level" class="vjs-volume-bar vjs-slider" tabindex="0" aria-valuemax="100" aria-valuemin="0" aria-valuenow="-1" role="slider"><div style="width: 0%;" class="vjs-volume-level"><span class="vjs-control-text"></span></div><div style="left: 0%;" class="vjs-volume-handle vjs-slider-handle"><span class="vjs-control-text">00:00</span></div></div></div><div tabindex="0" aria-live="polite" role="button" class="vjs-mute-control vjs-control vjs-vol-0"><div><span class="vjs-control-text">Unmute</span></div></div><div role="button" aria-haspopup="true" class="vjs-playback-rate vjs-menu-button vjs-control vjs-hidden"><div class="vjs-control-content"><span class="vjs-control-text">Playback Rate</span></div><div class="vjs-playback-rate-value">1</div><div class="vjs-menu"><ul class="vjs-menu-content"></ul></div></div><div aria-label="Subtitles Menu" style="display: none;" aria-haspopup="true" tabindex="0" aria-live="polite" role="button" class="vjs-subtitles-button vjs-menu-button vjs-control "><div class="vjs-control-content"><span class="vjs-control-text">Subtitles</span><div class="vjs-menu"><ul class="vjs-menu-content"><li aria-selected="true" tabindex="0" aria-live="polite" role="button" class="vjs-menu-item vjs-selected">subtitles off</li></ul></div></div></div><div aria-label="Captions Menu" style="display: none;" aria-haspopup="true" tabindex="0" aria-live="polite" role="button" class="vjs-captions-button vjs-menu-button vjs-control "><div class="vjs-control-content"><span class="vjs-control-text">Captions</span><div class="vjs-menu"><ul class="vjs-menu-content"><li aria-selected="true" tabindex="0" aria-live="polite" role="button" class="vjs-menu-item vjs-selected">captions off</li></ul></div></div></div><div aria-label="Chapters Menu" aria-haspopup="true" style="display: none;" tabindex="0" aria-live="polite" role="button" class="vjs-chapters-button vjs-menu-button vjs-control "><div class="vjs-control-content"><span class="vjs-control-text">Chapters</span><div class="vjs-menu"><ul class="vjs-menu-content"><li class="vjs-menu-title">Chapters</li></ul></div></div></div></div><div class="vjs-error-display"><div></div></div><div style="display: none;" class="popover-backdrop popover-backdrop-3"></div>

**Comment by xderry** [comment]
Please re-open if there is a problem.

If the problem exists, please re-open the bug, and report the issue according to:

https://github.com/hola/player#reporting-bugs
