### ISSUE TITLE
The player don't load the subtitles with appropriated encoding

### ISSUE THREAD

**Issue by legionaryu** [hola/player#5]
I was trying to load a subtitle in ANSI, but the player keeps trying to load them in UTF-8, so I converted the subtitles file to UTF-8, but I think that should be in the player functionality.

**Comment by arikgilad** [comment]
Thanks for your feedback.
We are going to fix this bug so we will auto-detect the encoding and in addition we will add feature to allow manual selection of the correct encoding.
We hope to fix those bug in the next few weeks.

**Comment by legionaryu** [comment]
Thanks!

**Comment by xavico** [comment]
we have auto-detection of the subtitles character encoding. But this auto-detection does not always work 100%.

If we would give you a feature that you can specify the encoding: example:

Force language Spanish, with UTF8 char encoding:
sub=es,utf8,http://.../xxx.srt

Force language Spanish with char encoding ISO 8859-1 (Latin-1)
sub=es,latin-1,http://.../xxx.srt

Will this solve for you the problem?

**Comment by legionaryu** [comment]
Yes, it would! Thanks

**Comment by samirios1** [comment]
as an official system for json as UTF-8 because I have problems of encoding and use json in the subtitles, sorry for my English

**Comment by xderry** [comment]
samirios1: I dont understand your comment.

Take a look at this sample:
play?v=...&sub=json,https://raw.githubusercontent.com/hola/player/master/res/sub2.json

Does this format solve your problem?
https://github.com/hola/player/blob/master/res/sub2.json

If no - what format do you need?

**Comment by xavico** [comment]
The bug was fixed. If you still encounter this problem please reopen this issue.
