### ISSUE TITLE
Subtitles' size

### ISSUE THREAD

**Issue by dominio12** [hola/player#6]
Currently the size of the subtitles is really small. Even by selecting the biggest size in settings it's still barely readable (I'm using my TV to watch movies from the PC). Could you please fix this? 
Excellent work by the way! 
Thanks!

**Comment by arikgilad** [comment]
Thanks for reporting this bug.
We expect to release a fix in the next few days.

**Comment by dominio12** [comment]
Thanks for your reply! I'll stay tuned then!

**Comment by michalzh** [comment]
We enlarged the subtitles font size 
Let us know if you encounter any additional issues 

Thanks again for your feedback

**Comment by dominio12** [comment]
I just tested it and the biggest font size is readable. But the others are
really really small (see screenshot attached). My suggestion would be to
make the current Biggest one (let's say font size 5) the middle one (say
font size 3), so the user can still have 2 bigger sizes to choose (and 2
smaller).

Thanks anyways for your time and the app!

Cheers,

Raul

2015-06-09 8:58 GMT-03:00 michalzh notifications@github.com:

**Comment by xavico** [comment]
Thanks for reporting this issue.
We expect to release a fix in the next two weeks.

**Comment by xavico** [comment]
We think we solved this issue. In the next couple of hours we will release it.

**Comment by xavico** [comment]
The bug was fixed. If you still encounter this problem please reopen this issue.
