### ISSUE TITLE
JW player integration dont work

### ISSUE THREAD

**Issue by toniojst** [hola/player#7]
Hello i go from step by step to integrate hola player and jwplayer but i cant do that this will work so can you send me one demo or something

**Comment by SharonMaydar** [comment]
Hello, 
Did you try to integrate Hola media player (hola/player) or Hola CDN (hola/cdn)?
I will be happy to show you a demo.
Thanks,
Sharon

**Comment by toniojst** [comment]
Look can you give me some demo code on jsbin or something becuse i am starter on html/js coding so i trying something but not work? Look hola player is good but if i can play with jwplayer then is been better.. So if you can give me some demo and simple code i will be very happy

**Comment by SharonMaydar** [comment]
Hi,
Please goto "live demo" links  on https://github.com/hola/player.
When pressing the live demo link you will be transferred to output.jsbin.com/xxx where you need to press the "Edit in JS Bin" in order to see the code.
Let me know if you need additional assistance.
Thanks, Sharon

**Comment by toniojst** [comment]
I dont found demo code for integration hola with jwplayer

**Comment by SharonMaydar** [comment]
Can you please share with me what are you trying to do? what is your use case?
I will try to assist you. 
Thanks,
Sharon

**Comment by toniojst** [comment]
this is my code but this dont work

```
                <script src="//hola.org/play_page.js"></script>
                <script src="//hola.org/play_loader.js"></script>
                <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.0/jquery.min.js"></script>

                <script>
                function hola_player_init(){
// XXX: set browser to enable hola player on specific browser
// (set browsers = [] to use hola on all compatible browser
// to enable only on speicfic browsers use:
// ['chrome', 'firefox'] or ['chrome windows', 'firefox windows'])
var browsers = [];
if (!window.hola_compatible_browser ||
    !window.hola_compatible_browser(browsers))
{
    return;
}
var $container = $('<div>').hide().appendTo($('body'))
.attr('style', 'position: absolute; z-index: 1000; '+
    'width: 100%; height: 100%; left: 50%; top: 50%');
$('#player_display_button, .jwpreview.jwbestfit')
.click(function(event){
    event.preventDefault();
    event.stopPropagation();
    $('#player_display').hide();
    // XXX: change opt values
    // v: full url of video to play
    // sources: array of multiple quality of the same video
    //  [{file: 'http://.../x.mp4', label: '720'], {file: 'http://.../x2.mp4', label: '480'}]
    // title: video title
    // pluign: full url of the subtitles plugin
    // container: the html element were to put the player
    // cdn: set to use hola peer network to save bandwidth
    window.hola_load_player({
        v: config.file,
        sources: config.sources,
        title: $($('.videotitle span')[0]).text(),
        subtitles: config.tracks,
        plugin_url: location.protocol+'//'+location.host+
            '/assets/js/hl_plugin.json',
        container: $container,
        cdn: true});
});
// XXX: add code to handle player events
window.addEventListener('message', function(e){
    if (!e.data || !e.data.id)
        return;
    if (!/hola_vjs\..*/.test(e.data.id))
        return;
});
```

}

function init_timer(){
    if (!$('#player_display_button') || !$('#player_display_button')[0]
        || !$('.jwpreview.jwbestfit') || !$('.jwpreview.jwbestfit')[0])
    {
        setTimeout(init_timer, 250);
        return;
    }
    hola_player_init();
}

init_timer();
                    </script>

```
                <script>window.hola_player.init({links: 'hover'});</script>
                <div 
                class="hola-embedded-player" 
                title="Video Title" 
                v="magnet:?xt=urn:btih:affc3a2bbb7da2fab119d1c85c20072b394db1cb&dn=Despicable+Me+2+%282013%29+1080p+BrRip+x264+-+YIFY&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969"
                ></div>


              <script src="http://jwpsrv.com/library/l4qjtGPjEeKNAiIACp8kUw.js"></script>
              <div id='playerTBYGfesnPtCE'></div>
```

<script type='text/javascript'>
    jwplayer('playerTBYGfesnPtCE').setup({
        file: 'http://www.quirksmode.org/html5/videos/big_buck_bunny.mp4',
        image: '//www.longtailvideo.com/content/images/jw-player/lWMJeVvV-876.jpg',
        title: 'film ime',
        width: '100%',
        aspectratio: '16:9'
    });
</script>

**Comment by SharonMaydar** [comment]
Hi,

Note that in the instructions we indicated that "The video today is taken from global config.file".
We updated the jwplayer.md with the following:

var config = jwplayer().config;
if (!config || !config.file)
    config = jwplayer().getPlaylistItem();
if (!config || !config.file) // XXX: change video to play
    config = {file: 'http://cdn4.hola.org/static/mp4/sintel.mp4'};

If you still have a problem, please send me your JSbin and I'll take a look.

Thanks,
Sharon

**Comment by toniojst** [comment]
Look i am starter on html and js coding so i dont know how to integrate and this toghether and i dont know what this code mean so i realy ... I just want that i can play torrent file with jwplayer

**Comment by SharonMaydar** [comment]
Hi,
Hola media player streams torrent files instantly. Please look at http://hola.org/player.
We do not support torrent steaming with jwplayer.

Thanks,
Sharon

**Comment by toniojst** [comment]
What then do the jw integration code?
